[2022-06-06 11:43:01,998] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:02,092] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:02,094] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:02,095] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 11:43:02,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:02,149] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_order_detail> on 2022-06-05 00:00:00+00:00
[2022-06-06 11:43:02,160] {standard_task_runner.py:52} INFO - Started process 3140 to run task
[2022-06-06 11:43:02,168] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'create_order_detail', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpk8a7nt3n', '--error-file', '/tmp/tmpq8p_dndy']
[2022-06-06 11:43:02,182] {standard_task_runner.py:80} INFO - Job 49: Subtask create_order_detail
[2022-06-06 11:43:02,313] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [running]> on host 0c241499c9fe
[2022-06-06 11:43:02,503] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=create_order_detail
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 11:43:02,566] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:43:02,720] {dbapi.py:208} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS order_detail (
    order_created_timestamp TIMESTAMP,
    status VARCHAR,
    price INT,
    discount FLOAT,
    id VARCHAR PRIMARY KEY NOT NULL,
    driver_id VARCHAR,
    user_id VARCHAR,
    restaurant_id VARCHAR
);, parameters: None
[2022-06-06 11:43:02,866] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=create_order_detail, execution_date=20220605T000000, start_date=20220606T114302, end_date=20220606T114302
[2022-06-06 11:43:03,559] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 11:43:03,858] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-06 12:14:44,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 12:14:44,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 12:14:44,485] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 12:14:44,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 12:14:44,487] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 12:14:44,506] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_order_detail> on 2022-06-05 00:00:00+00:00
[2022-06-06 12:14:44,515] {standard_task_runner.py:52} INFO - Started process 1921 to run task
[2022-06-06 12:14:44,521] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'create_order_detail', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0x8ou1o7', '--error-file', '/tmp/tmp614gayzj']
[2022-06-06 12:14:44,527] {standard_task_runner.py:80} INFO - Job 75: Subtask create_order_detail
[2022-06-06 12:14:44,606] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.create_order_detail scheduled__2022-06-05T00:00:00+00:00 [running]> on host 078df8b61ea1
[2022-06-06 12:14:44,725] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=create_order_detail
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 12:14:44,739] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 12:14:44,759] {dbapi.py:208} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS order_detail (
    order_created_timestamp TIMESTAMP,
    status VARCHAR,
    price INT,
    discount FLOAT,
    id VARCHAR PRIMARY KEY NOT NULL,
    driver_id VARCHAR,
    user_id VARCHAR,
    restaurant_id VARCHAR
);, parameters: None
[2022-06-06 12:14:44,797] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=create_order_detail, execution_date=20220605T000000, start_date=20220606T121444, end_date=20220606T121444
[2022-06-06 12:14:44,855] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 12:14:44,933] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
