[2022-06-10 06:57:43,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_restaurant_detail manual__2022-06-10T06:57:39.204816+00:00 [queued]>
[2022-06-10 06:57:43,304] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_restaurant_detail manual__2022-06-10T06:57:39.204816+00:00 [queued]>
[2022-06-10 06:57:43,305] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-10 06:57:43,307] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-10 06:57:43,309] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-10 06:57:43,344] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_restaurant_detail> on 2022-06-10 06:57:39.204816+00:00
[2022-06-10 06:57:43,354] {standard_task_runner.py:52} INFO - Started process 380 to run task
[2022-06-10 06:57:43,384] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'create_restaurant_detail', 'manual__2022-06-10T06:57:39.204816+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzzoasuko', '--error-file', '/tmp/tmpjal4hjgy']
[2022-06-10 06:57:43,392] {standard_task_runner.py:80} INFO - Job 11: Subtask create_restaurant_detail
[2022-06-10 06:57:43,678] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.create_restaurant_detail manual__2022-06-10T06:57:39.204816+00:00 [running]> on host a0fd966c00bf
[2022-06-10 06:57:43,934] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=create_restaurant_detail
AIRFLOW_CTX_EXECUTION_DATE=2022-06-10T06:57:39.204816+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-10T06:57:39.204816+00:00
[2022-06-10 06:57:43,988] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-10 06:57:44,047] {dbapi.py:208} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS restaurant_detail (
    id VARCHAR PRIMARY KEY NOT NULL,
    restaurant_name VARCHAR,
    category VARCHAR,
    estimated_cooking_time FLOAT,
    latitude FLOAT,
    longitude FLOAT
);, parameters: None
[2022-06-10 06:57:44,056] {postgres.py:94} INFO - NOTICE:  relation "restaurant_detail" already exists, skipping

[2022-06-10 06:57:44,163] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=create_restaurant_detail, execution_date=20220610T065739, start_date=20220610T065743, end_date=20220610T065744
[2022-06-10 06:57:44,207] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-10 06:57:44,421] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
