[2022-06-06 11:52:12,641] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-06T11:48:14.551686+00:00 [queued]>
[2022-06-06 11:52:12,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-06T11:48:14.551686+00:00 [queued]>
[2022-06-06 11:52:12,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:52:12,658] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2022-06-06 11:52:12,659] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:52:12,679] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): copy_restaurant_detail_data> on 2022-06-06 11:48:14.551686+00:00
[2022-06-06 11:52:12,686] {standard_task_runner.py:52} INFO - Started process 495 to run task
[2022-06-06 11:52:12,691] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_restaurant_detail_data', 'manual__2022-06-06T11:48:14.551686+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkjvlq_y2', '--error-file', '/tmp/tmp3xvbmauj']
[2022-06-06 11:52:12,693] {standard_task_runner.py:80} INFO - Job 70: Subtask copy_restaurant_detail_data
[2022-06-06 11:52:12,767] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-06T11:48:14.551686+00:00 [running]> on host 078df8b61ea1
[2022-06-06 11:52:12,860] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_restaurant_detail_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T11:48:14.551686+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-06T11:48:14.551686+00:00
[2022-06-06 11:52:12,873] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:52:12,885] {dbapi.py:208} INFO - Running statement: 
COPY restaurant_detail FROM '/var/lib/postgresql/data/restaurant_detail.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-06 11:52:12,890] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/var/lib/postgresql/data/restaurant_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-06-06 11:52:12,901] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=copy_restaurant_detail_data, execution_date=20220606T114814, start_date=20220606T115212, end_date=20220606T115212
[2022-06-06 11:52:12,918] {standard_task_runner.py:97} ERROR - Failed to execute job 70 for task copy_restaurant_detail_data (could not open file "/var/lib/postgresql/data/restaurant_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 495)
[2022-06-06 11:52:12,944] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 11:52:13,037] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
