[2022-06-07 09:24:49,650] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail manual__2022-06-07T09:24:47.019520+00:00 [queued]>
[2022-06-07 09:24:49,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_order_detail manual__2022-06-07T09:24:47.019520+00:00 [queued]>
[2022-06-07 09:24:49,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 09:24:49,674] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-07 09:24:49,675] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 09:24:49,720] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_order_detail> on 2022-06-07 09:24:47.019520+00:00
[2022-06-07 09:24:49,732] {standard_task_runner.py:52} INFO - Started process 18095 to run task
[2022-06-07 09:24:49,742] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'create_order_detail', 'manual__2022-06-07T09:24:47.019520+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpklviqw2q', '--error-file', '/tmp/tmp5sjx68sa']
[2022-06-07 09:24:49,745] {standard_task_runner.py:80} INFO - Job 81: Subtask create_order_detail
[2022-06-07 09:24:49,889] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.create_order_detail manual__2022-06-07T09:24:47.019520+00:00 [running]> on host a4a1e1d603db
[2022-06-07 09:24:50,101] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=create_order_detail
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T09:24:47.019520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-07T09:24:47.019520+00:00
[2022-06-07 09:24:50,136] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-07 09:24:50,153] {dbapi.py:208} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS order_detail (
    order_created_timestamp TIMESTAMP,
    status VARCHAR,
    price INT,
    discount FLOAT,
    id VARCHAR PRIMARY KEY NOT NULL,
    driver_id VARCHAR,
    user_id VARCHAR,
    restaurant_id VARCHAR
);, parameters: None
[2022-06-07 09:24:50,156] {postgres.py:94} INFO - NOTICE:  relation "order_detail" already exists, skipping

[2022-06-07 09:24:50,193] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=create_order_detail, execution_date=20220607T092447, start_date=20220607T092449, end_date=20220607T092450
[2022-06-07 09:24:50,245] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-07 09:24:50,446] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
